version: '3'

vars:
  BASE_DIR:
    sh: git rev-parse --show-toplevel

tasks:
  dev:build:
    desc: Build docker image for dev
    cmds:
      - /{{.BASE_DIR}}/dev/scripts/docker-build.sh
  dev:shell:
    desc: Run dev docker image and obtain shell
    cmds:
      - /{{.BASE_DIR}}/dev/scripts/docker-run.sh {{.CLI_ARGS}}
  dev:shell-reuse:
    desc: Obtain new shell in a currently running docker container
    cmds:
      - docker exec -it $(docker ps | grep jupyterlab-code-formatter-dev | cut -f1 -d' ') bash
  dev:serve-docs:
    desc: Serve docs
    cmds:
      - cd docs && python -m http.server 1234
  publish:
    desc: Publish package
    cmds:
      - /{{.BASE_DIR}}/bin/publish.sh
